### ISSUE TITLE
.pyblish image

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-ci#1]
Use `image` as opposed to `environment` as key to determine which Docker image to run tests within.
### Implementation

Proposed format.

``` yaml
image:
- mottosso/maya2015sp5
- mottosso/maya2016sp1
- mottosso/nuke8
- mottosso/nuke9
script:
- git clone https://github.com/pyblish/pyblish-x.git
- export PYTHONPATH=$(pwd)/pyblish-x/pythonpath
- python run_testsuite.py
```
